import net.proteanit.sql.DbUtils;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;

public class BBS
{
    private JTable table1;
    public JPanel panel1;
    private JButton zeitraum;
    private JButton umsatzsummenButton;
    private JButton offenePostenButton;
    private JButton miettageUmsatzButton;
    private static final String user = "root";
    private static final String password = "bbs";
    private static String url = "jdbc:mysql://localhost:3306/baumaschinen_malgin";
    private static Connection con;
    private static Statement stmt;
    private static ResultSet rs;
    String query = new String();
    String selectedtext;
    ArrayList<String> rownames = new ArrayList<String>();
    ArrayList<String> tables = new ArrayList<String>();

    public BBS()
    {
        zeitraum.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                try
                {
                    query = "select AuftrDat, Mietbeginn, Mietende, MaschinenNr, Name, bezahlt from tbl_kunden k, tbl_auftrag a, tbl_rechnung r where k.KdNr = a.KdNr and a.AuftrNr = r.AuftrNr and Mietbeginn between '2013-04-11' and '2013-04-15' and bezahlt = 1";
                    con = DriverManager.getConnection(url, user, password);
                    stmt = con.createStatement();
                    rs = stmt.executeQuery(query);
                    table1.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (Exception ex)
                {
                    JOptionPane.showMessageDialog(null, ex.toString());
                }
            }
        });
        umsatzsummenButton.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                try
                {
                    query = "select Name, sum(Betrag) as Umsatz from tbl_kunden k, tbl_auftrag a, tbl_rechnung r where k.KdNr = a.KdNr and a.AuftrNr = r.AuftrNr and bezahlt = 1 group by Name order by Name";
                    con = DriverManager.getConnection(url, user, password);
                    stmt = con.createStatement();
                    rs = stmt.executeQuery(query);
                    table1.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (Exception ex)
                {
                    JOptionPane.showMessageDialog(null, ex.toString());
                }
            }
        });
        offenePostenButton.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                try
                {
                    query = "select Name, count(RechNr) as 'Offene Posten' from tbl_kunden k, tbl_auftrag a, tbl_rechnung r where k.KdNr  = a.KdNr and a.AuftrNr = r.AuftrNr and bezahlt = 0 group by Name order by Name";
                    con = DriverManager.getConnection(url, user, password);
                    stmt = con.createStatement();
                    rs = stmt.executeQuery(query);
                    table1.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (Exception ex)
                {
                    JOptionPane.showMessageDialog(null, ex.toString());
                }
            }
        });
        miettageUmsatzButton.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                try
                {
                    query = "select Bezeichnung, (Mietende - Mietbeginn) as 'Miettage', (Mietpreis * (Mietende - Mietbeginn)) as Umsatzmaschinen from tbl_maschinen m, tbl_auftrag a where a.MaschinenNr = m.MaschinenNr";
                    con = DriverManager.getConnection(url, user, password);
                    stmt = con.createStatement();
                    rs = stmt.executeQuery(query);
                    table1.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (Exception ex)
                {
                    JOptionPane.showMessageDialog(null, ex.toString());
                }
            }
        });
    }

    public JPanel getPanel1()
    {
        return panel1;
    }



    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 4, new Insets(15, 15, 15, 15), -1, -1));
        table1 = new JTable();
        panel1.add(table1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 4, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 150), null, 0, false));
        zeitraum = new JButton();
        zeitraum.setText("Kunden im Zeitraum");
        panel1.add(zeitraum, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        umsatzsummenButton = new JButton();
        umsatzsummenButton.setText("Umsatzsummen");
        panel1.add(umsatzsummenButton, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        offenePostenButton = new JButton();
        offenePostenButton.setText("offene Posten");
        panel1.add(offenePostenButton, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        miettageUmsatzButton = new JButton();
        miettageUmsatzButton.setText("Miettage/Umsatz");
        panel1.add(miettageUmsatzButton, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(-1, 5), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return panel1;
    }
}


